/**
 * ============================================================
 * DATA CONVERSION — vanilla JS data files → React ES modules
 * ============================================================
 * Converts aws-lambda-masterclass/js/data/module-*.js into ES modules
 * under src/data/modules/, and courses.js into src/data/courseRegistry.json.
 *
 * Why ES modules instead of JSON for module data: the source data contains
 * executable callbacks (e.g. `onRun: () => ...`) which cannot be serialized.
 * A text transform (`const X =` → `export default`, strip UMD footer)
 * preserves 100% of the original content verbatim.
 *
 * Usage: node scripts/convert-data.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'aws-lambda-masterclass', 'js', 'data');
const CHAPTERS_DIR = path.join(ROOT, 'public', 'chapters');
const OUT_DIR = path.join(ROOT, 'src', 'data');
const MODULES_OUT = path.join(OUT_DIR, 'modules');

// The root package.json uses "type": "module", so `require()` would load
// courses.js as ESM and its `window.*` UMD branch would crash. Evaluate it in
// a shimmed CJS context instead.
function loadCjsModule(filePath) {
  const src = fs.readFileSync(filePath, 'utf8');
  const module = { exports: {} };
  const fn = new Function('module', 'exports', 'window', src);
  fn(module, module.exports, {});
  return module.exports;
}

// ── 1. Convert module-*.js data files → ES modules ─────────────────────────
const moduleFiles = fs.readdirSync(DATA_DIR)
  .filter(f => /^module-\d+-[\w-]+\.js$/.test(f))
  .sort();

if (moduleFiles.length === 0) {
  console.error('No module data files found in', DATA_DIR);
  process.exit(1);
}

fs.mkdirSync(MODULES_OUT, { recursive: true });

const moduleIndex = {}; // moduleId -> dataFile basename
const moduleMeta = {};  // moduleId -> { sectionCount }
const typeStats = {};   // section type -> total count across all modules
let quizQuestionCount = 0;
for (const file of moduleFiles) {
  const src = fs.readFileSync(path.join(DATA_DIR, file), 'utf8');

  // Locate the single top-level data declaration: const MODULE_XX_DATA = {...
  const declMatch = src.match(/^const\s+(MODULE_\w+)\s*=\s*/m);
  if (!declMatch) {
    console.error(`  ✗ ${file}: no top-level MODULE_* const found — skipped`);
    continue;
  }

  let out = src.slice(0, declMatch.index)
    + `const ${declMatch[1]} = `
    + src.slice(declMatch.index + declMatch[0].length);

  // Strip the UMD footer (module.exports / window assignment) if present
  out = out.replace(/\n?if\s*\(\s*typeof module\s*!==\s*'undefined'[\s\S]*$/m, '');

  out = out.trimEnd()
    + `\n\nexport default ${declMatch[1]};\n`;

  const outName = file; // keep module-01-iam.js naming
  fs.writeFileSync(path.join(MODULES_OUT, outName), out, 'utf8');

  // Evaluate the original file to recover moduleId + section count.
  // Some files lack the UMD footer — append an explicit export to be safe.
  const data = (() => {
    const module = { exports: {} };
    new Function('module', 'exports', 'window',
      src + `\n;module.exports = ${declMatch[1]};`)(module, module.exports, {});
    return module.exports;
  })();
  const moduleId = data?.moduleId || file.match(/^module-\d+/)?.[0];
  moduleIndex[moduleId] = outName.replace(/\.js$/, '');
  moduleMeta[moduleId] = { sectionCount: Array.isArray(data?.sections) ? data.sections.length : 0 };
  for (const s of data?.sections || []) {
    typeStats[s.type] = (typeStats[s.type] || 0) + 1;
    if (s.type === 'quiz') quizQuestionCount += (s.content?.questions || []).length;
  }
  console.log(`  ✓ ${file} → src/data/modules/${outName} (${moduleId}, ${moduleMeta[moduleId].sectionCount} sections)`);
}

// ── 2. Emit lazy-load index for code splitting ─────────────────────────────
const indexJs = `/**
 * ============================================================
 * MODULE DATA LOADERS — generated by scripts/convert-data.mjs
 * Maps moduleId → dynamic import() for per-chapter code splitting.
 * ============================================================
 */
export const moduleLoaders = {
${Object.entries(moduleIndex).map(([id, f]) => `  '${id}': () => import('./${f}.js'),`).join('\n')}
};
`;
fs.writeFileSync(path.join(MODULES_OUT, 'index.js'), indexJs, 'utf8');
console.log(`  ✓ module index (${Object.keys(moduleIndex).length} modules)`);

// ── 3. courses.js → courseRegistry.json (+ mdFile per module) ──────────────
const COURSE_REGISTRY = loadCjsModule(path.join(DATA_DIR, 'courses.js'));

const chapterFiles = fs.readdirSync(CHAPTERS_DIR);
const findChapterFile = (number) =>
  chapterFiles.find(f => f.startsWith(`Chapter_${number}_`)) || null;

const registry = {
  id: COURSE_REGISTRY.id,
  title: COURSE_REGISTRY.title,
  subtitle: COURSE_REGISTRY.subtitle,
  description: COURSE_REGISTRY.description,
  modules: (COURSE_REGISTRY.modules || []).map(m => ({
    ...m,
    href: undefined, // vanilla anchor href not needed in React Router app
    mdFile: findChapterFile(m.number),
    sectionCount: moduleMeta[m.id]?.sectionCount ?? 0,
  })),
  achievements: COURSE_REGISTRY.achievements || [],
  stats: {
    chapters: (COURSE_REGISTRY.modules || []).length,
    sections: Object.values(moduleMeta).reduce((s, m) => s + m.sectionCount, 0),
    labs: typeStats.lab || 0,
    quizzes: typeStats.quiz || 0,
    quizQuestions: quizQuestionCount,
    challenges: typeStats.challenge || 0,
    sectionTypes: typeStats,
  },
};

// Sanity: every module must resolve a chapter file
const missing = registry.modules.filter(m => !m.mdFile);
if (missing.length) {
  console.warn('  ⚠ Modules without a chapter markdown file:',
    missing.map(m => m.id).join(', '));
}

fs.writeFileSync(
  path.join(OUT_DIR, 'courseRegistry.json'),
  JSON.stringify(registry, null, 2) + '\n',
  'utf8'
);
console.log(`  ✓ courseRegistry.json (${registry.modules.length} modules)`);
console.log('Done.');
